### ISSUE TITLE
assign method under windows and charset issues

### ISSUE THREAD

**Issue by niederle** [s-u/REngine#24]
Hi,
I have a Java-Application running on Windows with an Rserve-client and the Rserve-server runs on an Ubuntu. I was observing issues when there are non-ascii characters involved and I detected a strange behaviour. I was running this little code snippet (connection = established RConnection):

`connection.assign("teststring1", new REXPString("entry1 µl"));`
	`connection.assign("teststring2", "entry2 µl");`
	`connection.voidEval("teststring3 <-  \"entry3 µl\"");`
`connection.voidEval("save(teststring1, teststring2, teststring3, file = \"/home/niederle/test.RData\")");`

If I open that RData-file in R, one can clearly see that the 'µ' character has been transferred differently. Additionally, it looks different when opening it under Mac or Windows.

<img width="270" alt="Screen Shot 2020-09-30 at 11 37 12" src="https://user-images.githubusercontent.com/740926/94683186-600c6e00-0326-11eb-911a-1e9230df6c43.png">
<img width="270" alt="Screen Shot 2020-09-30 at 11 37 19" src="https://user-images.githubusercontent.com/740926/94683210-6b5f9980-0326-11eb-9768-cb3eabb7fb1a.png">

To me it look like there is an encoding problem.

**Comment by s-u** [comment]
@niederle Thanks, the `assign()` methods did not re-encode string payload into the transfer encoding, so it passed the native encoding instead. I have attempted to fix that by adding the same re-coding for `assign()` in the master branch, please give it a go. You only need to update the client. Since the test class is in UTF-8 (and so is the native encoding) I can't really test this easily.

**Comment by s-u** [comment]
Added a test running in `de_DE.ISO8859-1` and it seems the fix works.
